name: xcodebuild

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  Xcode:
    strategy:
      matrix:
        xcode_version: ['15.3', '15.4', '16.1', '16.2']
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode_version }}
      - run: xcodebuild -version
      - run: xcodebuild -scheme SourceKitten-Package -parallel-testing-enabled NO test -destination platform=macOS
